import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "en" | "hi" | "mr" | "gu";

export const LANGUAGES: { code: Lang; label: string; native: string }[] = [
  { code: "en", label: "English", native: "English" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "mr", label: "Marathi", native: "मराठी" },
  { code: "gu", label: "Gujarati", native: "ગુજરાતી" },
];

type Dict = Record<string, string>;

const dictionaries: Record<Lang, Dict> = {
  en: {
    "nav.about": "About",
    "nav.materials": "Materials",
    "nav.features": "Features",
    "nav.sizes": "Sizes",
    "nav.contact": "Contact",
    "nav.enquire": "Enquire Now",
    "hero.tag": "Sustainable Solutions",
    "hero.title1": "Replacing Plastic,",
    "hero.title2": "Empowering India",
    "hero.sub": "Compostable bags — the future of sustainable packaging. Crafted from corn starch & natural polymers, certified for a cleaner tomorrow.",
    "hero.cta1": "Explore Bag Sizes",
    "hero.cta2": "Learn More",
    "hero.notice1.title": "Say No To Plastic",
    "hero.notice1.desc": "For the betterment of our future generation",
    "hero.notice2.title": "Biodegradable Bags",
    "hero.notice2.desc": "Biodegradable bags are Ecofriendly",
    "cert.madeIndia": "Made in India",
    "cert.compostable": "100% Compostable",
    "cert.iso": "ISO 17088:2021 Certified",
    "cert.fssai": "FSSAI / CPCB Compliant",
    "about.kicker": "About Bactofun Bags",
    "about.title": "The Future of Sustainable Packaging",
    "about.sub": "We are on a mission to replace single-use plastic with truly compostable alternatives — engineered from plant-based materials, designed for everyday use, and certified safe for soil and sea.",
    "materials.kicker": "What's Inside",
    "materials.title": "Crafted from Nature, Returns to Nature",
    "materials.sub": "Every Bactofun Bag is a precise blend of plant-derived ingredients — engineered to perform like plastic, then quietly compost back to soil.",
    "materials.card1.name": "Corn Starch",
    "materials.card1.role": "Primary Base",
    "materials.card1.desc": "Abundant, low-cost agricultural feedstock that forms the bag's compostable backbone.",
    "materials.card2.name": "PLA (Polylactic Acid)",
    "materials.card2.role": "Strength",
    "materials.card2.desc": "Fermented plant sugars that deliver tensile strength and durability for everyday loads.",
    "materials.card3.name": "PBAT",
    "materials.card3.role": "Flexibility",
    "materials.card3.desc": "Biodegradable polymer that adds flexibility and tear resistance — fully decomposes in soil.",
    "materials.card4.name": "Natural Additives",
    "materials.card4.role": "Plasticizer",
    "materials.card4.desc": "Plant-based plasticizers and natural additives that fine-tune texture and performance.",
    "features.kicker": "Why Choose Us",
    "features.title": "Better for You. Better for the Planet.",
    "features.card1.title": "100% Compostable",
    "features.card1.desc": "Breaks down into water, CO2 and biomass — leaving no microplastics behind.",
    "features.card2.title": "ISO 17088:2021 Certified",
    "features.card2.desc": "Internationally certified compostable — also CPCB approved & FSSAI food-safe.",
    "features.card3.title": "Plant-Based Origin",
    "features.card3.desc": "Made from renewable corn starch & PLA — not fossil fuels.",
    "features.card4.title": "Strong & Leak-Proof",
    "features.card4.desc": "Engineered for daily use — carries up to 10 KG with confidence.",
    "features.card5.title": "Made in India",
    "features.card5.desc": "Proudly manufactured in India, supporting local industry & farmers.",
    "features.card6.title": "Safe for All",
    "features.card6.desc": "Non-toxic, food-safe & marine-life friendly — gentle on every ecosystem.",
    "sizes.kicker": "Bag Sizes",
    "sizes.title": "Find Your Perfect Fit",
    "sizes.sub": "All sizes are 100% compostable & ISO 17088:2021 certified — from kirana stores to retail chains.",
    "sizes.chartTitle": "SIZE CHART",
    "sizes.chartSub": "Compostable Carry Bag",
    "sizes.colSize": "Size in Inches",
    "sizes.colMicron": "Micron",
    "sizes.colPcs": "Nos. of Pcs (Apx)",
    "sizes.colLoad": "Load Capacity",
    "sizes.custom": "Need custom sizes or bulk pricing?",
    "cta.enquiry": "Send Requirement Enquiry",
    "contact.kicker": "Our Partners",
    "contact.title": "Meet the Partners",
    "contact.sub": "Reach out to our partners directly — we love hearing from distributors and conscious businesses.",
    "vision.kicker": "Our Vision",
    "vision.title": "A Sustainable Future We Can Build Together",
    "vision.goalsTitle": "3-Year Impact Goals",
    "vision.goal1.value": "100M",
    "vision.goal1.label": "Plastic bags replaced annually",
    "vision.goal2.value": "5,000",
    "vision.goal2.label": "Tonnes waste diverted from landfills",
    "vision.goal3.value": "500+",
    "vision.goal3.label": "Green jobs created",
    "vision.goal4.value": "1,000+",
    "vision.goal4.label": "Farmers supported via sourcing",
    "vision.nationalTitle": "Contributing to National Goals",
    "vision.national1.title": "Net-Zero by 2070",
    "vision.national1.desc": "Reducing carbon footprint through biodegradable alternatives.",
    "vision.national2.title": "Swachh Bharat Mission",
    "vision.national2.desc": "Supporting clean India initiatives through waste reduction.",
    "vision.national3.title": "Circular Economy",
    "vision.national3.desc": "Promoting sustainable production and consumption patterns.",
    "vision.national4.title": "UN SDGs",
    "vision.national4.desc": "Contributing to SDG 12 (Responsible Consumption) and SDG 13 (Climate Action).",
    "vision.bannerTitle": "Building a sustainable future through innovation and environmental stewardship",
    "vision.bannerCaption": "Scalable alternatives matter when they support industry, communities, and the planet at the same time.",
    "vision.whyTitle": "Why Bactofun Bags Matter",
    "vision.why1.label": "Environmental Crisis:",
    "vision.why1.desc": "India generates 25,000 tons of plastic waste daily. We’re part of the solution.",
    "vision.why2.label": "Regulatory Pressure:",
    "vision.why2.desc": "The 2022 plastic ban creates urgent demand for compliant alternatives.",
    "vision.why3.label": "Market Opportunity:",
    "vision.why3.desc": "A $2.7B market growing at 12.08% CAGR presents major scale potential.",
    "vision.why4.label": "Social Impact:",
    "vision.why4.desc": "Creating green jobs and supporting farmer livelihoods.",
    "vision.why5.label": "Future-Ready:",
    "vision.why5.desc": "Positioning India as a leader in sustainable packaging innovation.",
    "vision.commitTitle": "Our Commitment",
    "vision.commit1": "Quality excellence",
    "vision.commit2": "Transparent sourcing",
    "vision.commit3": "Certified products",
    "vision.commit4": "Customer partnership",
    "lang.label": "Language",
  },
  hi: {
    "nav.about": "हमारे बारे में",
    "nav.materials": "सामग्री",
    "nav.features": "विशेषताएँ",
    "nav.sizes": "साइज़",
    "nav.contact": "संपर्क",
    "nav.enquire": "पूछताछ करें",
    "hero.tag": "टिकाऊ समाधान",
    "hero.title1": "प्लास्टिक की जगह,",
    "hero.title2": "भारत को सशक्त बनाना",
    "hero.sub": "कम्पोस्टेबल बैग — टिकाऊ पैकेजिंग का भविष्य। मक्के के स्टार्च और प्राकृतिक पॉलिमर से बने, स्वच्छ कल के लिए प्रमाणित।",
    "hero.cta1": "बैग साइज़ देखें",
    "hero.cta2": "और जानें",
    "hero.notice1.title": "प्लास्टिक को ना कहें",
    "hero.notice1.desc": "हमारी भविष्य पीढ़ी के बेहतर कल के लिए",
    "hero.notice2.title": "बायोडिग्रेडेबल बैग",
    "hero.notice2.desc": "बायोडिग्रेडेबल बैग पर्यावरण अनुकूल हैं",
    "cert.madeIndia": "मेड इन इंडिया",
    "cert.compostable": "100% कम्पोस्टेबल",
    "cert.iso": "ISO 17088:2021 प्रमाणित",
    "cert.fssai": "FSSAI / CPCB अनुपालन",
    "about.kicker": "Bactofun Bags के बारे में",
    "about.title": "टिकाऊ पैकेजिंग का भविष्य",
    "about.sub": "हम सिंगल-यूज़ प्लास्टिक को सच्चे कम्पोस्टेबल विकल्पों से बदलने के मिशन पर हैं — पौधों से बने, रोज़मर्रा के लिए डिज़ाइन किए गए, और मिट्टी व समुद्र के लिए सुरक्षित प्रमाणित।",
    "materials.kicker": "अंदर क्या है",
    "materials.title": "प्रकृति से बना, प्रकृति में वापस",
    "materials.sub": "हर Bactofun Bag पौध-आधारित सामग्री का सटीक मिश्रण है — प्लास्टिक जैसा प्रदर्शन, फिर चुपचाप मिट्टी में मिल जाता है।",
    "materials.card1.name": "कॉर्न स्टार्च",
    "materials.card1.role": "मुख्य आधार",
    "materials.card1.desc": "प्रचुर मात्रा में मिलने वाला, कम लागत का कृषि कच्चा माल जो बैग की कम्पोस्टेबल मूल संरचना बनाता है।",
    "materials.card2.name": "PLA (पॉलीलैक्टिक एसिड)",
    "materials.card2.role": "मजबूती",
    "materials.card2.desc": "किण्वित पौध शर्करा जो रोजमर्रा उपयोग के लिए तन्य मजबूती और टिकाऊपन देती है।",
    "materials.card3.name": "PBAT",
    "materials.card3.role": "लचीलापन",
    "materials.card3.desc": "जैविक रूप से अपघटित पॉलिमर जो लचीलापन और फटने से बचाव बढ़ाता है — मिट्टी में पूरी तरह विघटित हो जाता है।",
    "materials.card4.name": "प्राकृतिक एडिटिव्स",
    "materials.card4.role": "प्लास्टिसाइज़र",
    "materials.card4.desc": "पौध-आधारित प्लास्टिसाइज़र और प्राकृतिक एडिटिव्स जो बनावट और प्रदर्शन को संतुलित करते हैं।",
    "features.kicker": "हमें क्यों चुनें",
    "features.title": "आपके लिए बेहतर। ग्रह के लिए बेहतर।",
    "features.card1.title": "100% कम्पोस्टेबल",
    "features.card1.desc": "पानी, CO2 और जैविक पिंड में विघटित होता है — कोई माइक्रोप्लास्टिक नहीं छोड़ता।",
    "features.card2.title": "ISO 17088:2021 प्रमाणित",
    "features.card2.desc": "अंतरराष्ट्रीय रूप से प्रमाणित कम्पोस्टेबल — CPCB अनुमोदित और FSSAI फूड-सेफ भी।",
    "features.card3.title": "पौध-आधारित उत्पत्ति",
    "features.card3.desc": "नवीकरणीय कॉर्न स्टार्च और PLA से बना — जीवाश्म ईंधन से नहीं।",
    "features.card4.title": "मजबूत और लीक-प्रूफ",
    "features.card4.desc": "रोजमर्रा उपयोग के लिए इंजीनियर किया गया — 10 KG तक का वजन आत्मविश्वास के साथ उठाता है।",
    "features.card5.title": "मेड इन इंडिया",
    "features.card5.desc": "गर्व से भारत में निर्मित, स्थानीय उद्योग और किसानों का समर्थन करता है।",
    "features.card6.title": "सबके लिए सुरक्षित",
    "features.card6.desc": "गैर-विषाक्त, फूड-सेफ और समुद्री जीवन के अनुकूल — हर पारिस्थितिकी तंत्र के लिए कोमल।",
    "sizes.kicker": "बैग साइज़",
    "sizes.title": "अपना सही साइज़ चुनें",
    "sizes.sub": "सभी साइज़ 100% कम्पोस्टेबल और ISO 17088:2021 प्रमाणित — किराना दुकान से रिटेल चेन तक।",
    "sizes.chartTitle": "साइज़ चार्ट",
    "sizes.chartSub": "कम्पोस्टेबल कैरी बैग",
    "sizes.colSize": "साइज़ (इंच में)",
    "sizes.colMicron": "माइक्रोन",
    "sizes.colPcs": "पीस की संख्या (लगभग)",
    "sizes.colLoad": "लोड क्षमता",
    "sizes.custom": "कस्टम साइज़ या थोक मूल्य चाहिए?",
    "cta.enquiry": "पूछताछ भेजें",
    "contact.kicker": "हमारे पार्टनर",
    "contact.title": "पार्टनर्स से मिलें",
    "contact.sub": "हमारे पार्टनर्स से सीधे संपर्क करें — हमें वितरकों और जागरूक व्यवसायों से सुनना अच्छा लगता है।",
    "vision.kicker": "हमारी दृष्टि",
    "vision.title": "एक टिकाऊ भविष्य जिसे हम मिलकर बना सकते हैं",
    "vision.goalsTitle": "3-वर्षीय प्रभाव लक्ष्य",
    "vision.goal1.value": "100M",
    "vision.goal1.label": "प्रतिवर्ष बदले गए प्लास्टिक बैग",
    "vision.goal2.value": "5,000",
    "vision.goal2.label": "लैंडफिल से हटाया गया अपशिष्ट (टन)",
    "vision.goal3.value": "500+",
    "vision.goal3.label": "सृजित ग्रीन रोजगार",
    "vision.goal4.value": "1,000+",
    "vision.goal4.label": "सोर्सिंग के माध्यम से समर्थित किसान",
    "vision.nationalTitle": "राष्ट्रीय लक्ष्यों में योगदान",
    "vision.national1.title": "2070 तक नेट-ज़ीरो",
    "vision.national1.desc": "जैव-अवघटनशील विकल्पों के माध्यम से कार्बन फुटप्रिंट कम करना।",
    "vision.national2.title": "स्वच्छ भारत मिशन",
    "vision.national2.desc": "अपशिष्ट कम करने के माध्यम से स्वच्छ भारत पहलों का समर्थन।",
    "vision.national3.title": "सर्कुलर इकोनॉमी",
    "vision.national3.desc": "टिकाऊ उत्पादन और उपभोग पैटर्न को बढ़ावा देना।",
    "vision.national4.title": "UN SDGs",
    "vision.national4.desc": "SDG 12 (जिम्मेदार उपभोग) और SDG 13 (जलवायु कार्रवाई) में योगदान।",
    "vision.bannerTitle": "नवाचार और पर्यावरणीय जिम्मेदारी के माध्यम से एक टिकाऊ भविष्य का निर्माण",
    "vision.bannerCaption": "स्केलेबल विकल्प तभी मायने रखते हैं जब वे उद्योग, समुदाय और पृथ्वी तीनों का साथ दें।",
    "vision.whyTitle": "Bactofun Bags क्यों मायने रखते हैं",
    "vision.why1.label": "पर्यावरणीय संकट:",
    "vision.why1.desc": "भारत हर दिन 25,000 टन प्लास्टिक कचरा उत्पन्न करता है। हम समाधान का हिस्सा हैं।",
    "vision.why2.label": "नियामक दबाव:",
    "vision.why2.desc": "2022 का प्लास्टिक प्रतिबंध अनुरूप विकल्पों की तत्काल मांग बनाता है।",
    "vision.why3.label": "बाज़ार अवसर:",
    "vision.why3.desc": "$2.7B का बाज़ार 12.08% CAGR पर बढ़ रहा है, जो बड़े पैमाने पर विकास की संभावना दिखाता है।",
    "vision.why4.label": "सामाजिक प्रभाव:",
    "vision.why4.desc": "ग्रीन जॉब्स का सृजन और किसानों की आजीविका का समर्थन।",
    "vision.why5.label": "भविष्य-तैयार:",
    "vision.why5.desc": "भारत को टिकाऊ पैकेजिंग नवाचार में अग्रणी बनाना।",
    "vision.commitTitle": "हमारी प्रतिबद्धता",
    "vision.commit1": "गुणवत्ता में उत्कृष्टता",
    "vision.commit2": "पारदर्शी सोर्सिंग",
    "vision.commit3": "प्रमाणित उत्पाद",
    "vision.commit4": "ग्राहक साझेदारी",
    "lang.label": "भाषा",
  },
  mr: {
    "nav.about": "आमच्याबद्दल",
    "nav.materials": "साहित्य",
    "nav.features": "वैशिष्ट्ये",
    "nav.sizes": "आकार",
    "nav.contact": "संपर्क",
    "nav.enquire": "चौकशी करा",
    "hero.tag": "शाश्वत उपाय",
    "hero.title1": "प्लास्टिकची जागा,",
    "hero.title2": "भारताला सशक्त बनवणे",
    "hero.sub": "कंपोस्टेबल बॅग्स — शाश्वत पॅकेजिंगचे भविष्य. मक्याच्या स्टार्च व नैसर्गिक पॉलिमरपासून बनवलेले, स्वच्छ उद्यासाठी प्रमाणित.",
    "hero.cta1": "बॅग आकार पहा",
    "hero.cta2": "अधिक जाणून घ्या",
    "hero.notice1.title": "प्लास्टिकला ना म्हणा",
    "hero.notice1.desc": "आपल्या भविष्य पिढीच्या चांगल्या भविष्यासाठी",
    "hero.notice2.title": "बायोडिग्रेडेबल बॅग्स",
    "hero.notice2.desc": "बायोडिग्रेडेबल बॅग्स पर्यावरणपूरक आहेत",
    "cert.madeIndia": "मेड इन इंडिया",
    "cert.compostable": "100% कंपोस्टेबल",
    "cert.iso": "ISO 17088:2021 प्रमाणित",
    "cert.fssai": "FSSAI / CPCB अनुरूप",
    "about.kicker": "Bactofun Bags बद्दल",
    "about.title": "शाश्वत पॅकेजिंगचे भविष्य",
    "about.sub": "एकेरी वापराच्या प्लास्टिकला खऱ्या कंपोस्टेबल पर्यायांनी बदलण्याचे आमचे ध्येय आहे — वनस्पतींपासून बनवलेले, दैनंदिन वापरासाठी डिझाइन केलेले, माती व समुद्रासाठी सुरक्षित प्रमाणित.",
    "materials.kicker": "आत काय आहे",
    "materials.title": "निसर्गातून बनलेले, निसर्गाकडे परत",
    "materials.sub": "प्रत्येक Bactofun Bag वनस्पती-आधारित घटकांचे अचूक मिश्रण आहे — प्लास्टिकसारखे काम करते, नंतर शांतपणे मातीत मिसळते.",
    "materials.card1.name": "कॉर्न स्टार्च",
    "materials.card1.role": "मूळ आधार",
    "materials.card1.desc": "बॅगच्या कंपोस्टेबल रचनेचा कणा बनवणारा, मुबलक आणि परवडणारा कृषी कच्चामाल.",
    "materials.card2.name": "PLA (पॉलीलॅक्टिक अॅसिड)",
    "materials.card2.role": "बळकटपणा",
    "materials.card2.desc": "दैनंदिन वापरासाठी ताणसहनशक्ती आणि टिकाऊपणा देणारी आंबवलेली वनस्पती साखर.",
    "materials.card3.name": "PBAT",
    "materials.card3.role": "लवचिकता",
    "materials.card3.desc": "लवचिकता आणि फाटण्यावरील प्रतिकार वाढवणारा जैवविघटनशील पॉलिमर, जो मातीत पूर्णपणे विघटित होतो.",
    "materials.card4.name": "नैसर्गिक अॅडिटिव्ह्स",
    "materials.card4.role": "प्लास्टिसायझर",
    "materials.card4.desc": "पोत आणि कार्यक्षमता सुसूत्र करणारे वनस्पती-आधारित प्लास्टिसायझर आणि नैसर्गिक अॅडिटिव्ह्स.",
    "features.kicker": "आम्हाला का निवडावे",
    "features.title": "तुमच्यासाठी उत्तम. ग्रहासाठी उत्तम.",
    "features.card1.title": "100% कंपोस्टेबल",
    "features.card1.desc": "पाणी, CO2 आणि जैवराशीमध्ये विघटित होते — सूक्ष्म प्लास्टिक मागे ठेवत नाही.",
    "features.card2.title": "ISO 17088:2021 प्रमाणित",
    "features.card2.desc": "आंतरराष्ट्रीयदृष्ट्या प्रमाणित कंपोस्टेबल — CPCB मान्यताप्राप्त आणि FSSAI फूड-सेफ.",
    "features.card3.title": "वनस्पती-आधारित उत्पत्ती",
    "features.card3.desc": "नवीकरणक्षम कॉर्न स्टार्च आणि PLA पासून तयार — जीवाश्म इंधन नव्हे.",
    "features.card4.title": "मजबूत आणि लीक-प्रूफ",
    "features.card4.desc": "दैनंदिन वापरासाठी अभियांत्रिक रीतीने तयार — 10 KG पर्यंत वजन आत्मविश्वासाने वाहते.",
    "features.card5.title": "मेड इन इंडिया",
    "features.card5.desc": "गर्वाने भारतात उत्पादित, स्थानिक उद्योग आणि शेतकऱ्यांना पाठबळ देणारे.",
    "features.card6.title": "सर्वांसाठी सुरक्षित",
    "features.card6.desc": "अविषारी, फूड-सेफ आणि सागरी जीवनास अनुकूल — प्रत्येक परिसंस्थेसाठी सौम्य.",
    "sizes.kicker": "बॅग आकार",
    "sizes.title": "तुमचा योग्य आकार शोधा",
    "sizes.sub": "सर्व आकार 100% कंपोस्टेबल व ISO 17088:2021 प्रमाणित — किराणा दुकानांपासून रिटेल चेनपर्यंत.",
    "sizes.chartTitle": "साइज़ चार्ट",
    "sizes.chartSub": "कंपोस्टेबल कॅरी बॅग",
    "sizes.colSize": "आकार (इंच)",
    "sizes.colMicron": "मायक्रॉन",
    "sizes.colPcs": "नग संख्या (अंदाजे)",
    "sizes.colLoad": "लोड क्षमता",
    "sizes.custom": "कस्टम आकार किंवा घाऊक दर हवे आहेत?",
    "cta.enquiry": "चौकशी पाठवा",
    "contact.kicker": "आमचे पार्टनर",
    "contact.title": "पार्टनर्सना भेटा",
    "contact.sub": "आमच्या पार्टनर्सशी थेट संपर्क साधा — वितरक व जागरूक व्यवसायांकडून ऐकायला आम्हाला आवडते.",
    "vision.kicker": "आमची दृष्टी",
    "vision.title": "आपण एकत्र घडवू शकतो असे शाश्वत भविष्य",
    "vision.goalsTitle": "3-वर्षीय प्रभाव लक्ष्ये",
    "vision.goal1.value": "100M",
    "vision.goal1.label": "दरवर्षी बदलल्या जाणाऱ्या प्लास्टिक पिशव्या",
    "vision.goal2.value": "5,000",
    "vision.goal2.label": "लँडफिलमध्ये जाणारा कचरा वळवला (टन)",
    "vision.goal3.value": "500+",
    "vision.goal3.label": "निर्माण होणाऱ्या ग्रीन नोकऱ्या",
    "vision.goal4.value": "1,000+",
    "vision.goal4.label": "सोर्सिंगमुळे समर्थन मिळालेले शेतकरी",
    "vision.nationalTitle": "राष्ट्रीय लक्ष्यांमध्ये योगदान",
    "vision.national1.title": "2070 पर्यंत Net-Zero",
    "vision.national1.desc": "जैवविघटनशील पर्यायांमुळे कार्बन फुटप्रिंट कमी करणे.",
    "vision.national2.title": "स्वच्छ भारत मिशन",
    "vision.national2.desc": "कचरा कमी करत स्वच्छ भारत उपक्रमांना पाठबळ देणे.",
    "vision.national3.title": "सर्क्युलर इकॉनॉमी",
    "vision.national3.desc": "शाश्वत उत्पादन आणि उपभोग पद्धतींना चालना देणे.",
    "vision.national4.title": "UN SDGs",
    "vision.national4.desc": "SDG 12 (जबाबदार उपभोग) आणि SDG 13 (हवामान कृती) मध्ये योगदान.",
    "vision.bannerTitle": "नवोपक्रम आणि पर्यावरणीय जबाबदारीतून शाश्वत भविष्य घडवणे",
    "vision.bannerCaption": "उद्योग, समुदाय आणि पृथ्वी या तिन्हींना साथ देणारे स्केलेबल पर्यायच खरे महत्त्वाचे ठरतात.",
    "vision.whyTitle": "Bactofun Bags का महत्त्वाचे आहेत",
    "vision.why1.label": "पर्यावरणीय संकट:",
    "vision.why1.desc": "भारतात दररोज 25,000 टन प्लास्टिक कचरा निर्मित होतो. आम्ही उपायाचा भाग आहोत.",
    "vision.why2.label": "नियामक दबाव:",
    "vision.why2.desc": "2022 च्या प्लास्टिक बंदीमुळे अनुरूप पर्यायांची तातडीची मागणी निर्माण होते.",
    "vision.why3.label": "बाजार संधी:",
    "vision.why3.desc": "$2.7B चा बाजार 12.08% CAGR ने वाढत आहे, जे मोठ्या प्रमाणात वाढीची संभावना दर्शवते.",
    "vision.why4.label": "सामाजिक प्रभाव:",
    "vision.why4.desc": "हरित रोजगार निर्माण करणे आणि शेतकऱ्यांच्या उपजीविकेला हातभार लावणे.",
    "vision.why5.label": "भविष्यासाठी तयार:",
    "vision.why5.desc": "भारताला शाश्वत पॅकेजिंग नवोपक्रमात अग्रणी म्हणून स्थान देणे.",
    "vision.commitTitle": "आमची बांधिलकी",
    "vision.commit1": "गुणवत्तेत उत्कृष्टता",
    "vision.commit2": "पारदर्शक सोर्सिंग",
    "vision.commit3": "प्रमाणित उत्पादने",
    "vision.commit4": "ग्राहक भागीदारी",
    "lang.label": "भाषा",
  },
  gu: {
    "nav.about": "અમારા વિશે",
    "nav.materials": "સામગ્રી",
    "nav.features": "વિશેષતાઓ",
    "nav.sizes": "સાઇઝ",
    "nav.contact": "સંપર્ક",
    "nav.enquire": "પૂછપરછ કરો",
    "hero.tag": "ટકાઉ ઉકેલો",
    "hero.title1": "પ્લાસ્ટિકનું સ્થાન,",
    "hero.title2": "ભારતને સશક્ત બનાવવું",
    "hero.sub": "કમ્પોસ્ટેબલ બેગ — ટકાઉ પેકેજિંગનું ભવિષ્ય. મકાઈના સ્ટાર્ચ અને કુદરતી પોલિમરમાંથી બનાવેલ, સ્વચ્છ આવતીકાલ માટે પ્રમાણિત.",
    "hero.cta1": "બેગ સાઇઝ જુઓ",
    "hero.cta2": "વધુ જાણો",
    "hero.notice1.title": "પ્લાસ્ટિકને ના કહો",
    "hero.notice1.desc": "આપણી આવતી પેઢીના સારા ભવિષ્ય માટે",
    "hero.notice2.title": "બાયોડીગ્રેડેબલ બેગ",
    "hero.notice2.desc": "બાયોડીગ્રેડેબલ બેગ પર્યાવરણ મિત્ર છે",
    "cert.madeIndia": "મેડ ઇન ઇન્ડિયા",
    "cert.compostable": "100% કમ્પોસ્ટેબલ",
    "cert.iso": "ISO 17088:2021 પ્રમાણિત",
    "cert.fssai": "FSSAI / CPCB અનુરૂપ",
    "about.kicker": "Bactofun Bags વિશે",
    "about.title": "ટકાઉ પેકેજિંગનું ભવિષ્ય",
    "about.sub": "અમે સિંગલ-યુઝ પ્લાસ્ટિકને સાચા કમ્પોસ્ટેબલ વિકલ્પોથી બદલવાના મિશન પર છીએ — છોડ આધારિત સામગ્રીમાંથી બનાવેલ, રોજિંદા ઉપયોગ માટે ડિઝાઇન કરેલ, માટી અને દરિયા માટે સુરક્ષિત પ્રમાણિત.",
    "materials.kicker": "અંદર શું છે",
    "materials.title": "કુદરતમાં થી બનેલ, કુદરતમાં પાછું",
    "materials.sub": "દરેક Bactofun Bag છોડ આધારિત ઘટકોનું ચોક્કસ મિશ્રણ છે — પ્લાસ્ટિક જેવું પ્રદર્શન, પછી શાંતિથી માટીમાં ભળી જાય.",
    "materials.card1.name": "કોર્ન સ્ટાર્ચ",
    "materials.card1.role": "મુખ્ય આધાર",
    "materials.card1.desc": "થેલીના કમ્પોસ્ટેબલ માળખાને આકાર આપતું પુષ્કળ અને ઓછા ખર્ચવાળું કૃષિ કાચું માલ.",
    "materials.card2.name": "PLA (પોલીલેક્ટિક એસિડ)",
    "materials.card2.role": "મજબૂતી",
    "materials.card2.desc": "આથો આપેલ વનસ્પતિ શર્કરાઓ જે રોજિંદા ઉપયોગ માટે તાણ સહનશક્તિ અને ટકાઉપણું આપે છે.",
    "materials.card3.name": "PBAT",
    "materials.card3.role": "લચીલાપણું",
    "materials.card3.desc": "જૈવિક રીતે વિઘટિત થતું પોલિમર જે લચીલાપણું અને ફાટવા સામેની ક્ષમતા વધારે છે — માટીમાં સંપૂર્ણ રીતે વિઘટિત થાય છે.",
    "materials.card4.name": "કુદરતી એડિટિવ્સ",
    "materials.card4.role": "પ્લાસ્ટિસાઇઝર",
    "materials.card4.desc": "વનસ્પતિ-આધારિત પ્લાસ્ટિસાઇઝર અને કુદરતી એડિટિવ્સ જે ઘડતર અને કાર્યક્ષમતાને સુમેળપૂર્ણ બનાવે છે.",
    "features.kicker": "અમને કેમ પસંદ કરો",
    "features.title": "તમારા માટે વધુ સારું. પૃથ્વી માટે વધુ સારું.",
    "features.card1.title": "100% કમ્પોસ્ટેબલ",
    "features.card1.desc": "પાણી, CO2 અને જૈવરાશિમાં વિઘટિત થાય છે — માઇક્રોપ્લાસ્ટિક પાછળ નથી છોડતું.",
    "features.card2.title": "ISO 17088:2021 પ્રમાણિત",
    "features.card2.desc": "આંતરરાષ્ટ્રીય રીતે પ્રમાણિત કમ્પોસ્ટેબલ — CPCB મંજૂર અને FSSAI ફૂડ-સેફ પણ.",
    "features.card3.title": "વનસ્પતિ-આધારિત મૂળ",
    "features.card3.desc": "નવીકરણક્ષમ કોર્ન સ્ટાર્ચ અને PLA માંથી બનાવેલ — અતેલ ઇંધણ પર આધારિત નથી.",
    "features.card4.title": "મજબૂત અને લિક-પ્રૂફ",
    "features.card4.desc": "રોજિંદા ઉપયોગ માટે એન્જિનિયર કરેલ છે — 10 KG સુધીનો ભાર આત્મવિશ્વાસપૂર્વક વહન કરે છે.",
    "features.card5.title": "મેડ ઇન ઇન્ડિયા",
    "features.card5.desc": "ગર્વથી ભારતમાં બનાવેલ, સ્થાનિક ઉદ્યોગ અને ખેડુતોને ટેકો આપતું.",
    "features.card6.title": "બધા માટે સુરક્ષિત",
    "features.card6.desc": "બિન-ઝેરી, ફૂડ-સેફ અને દરિયાઈ જીવન મિત્ર — દરેક પર્યાવરણ તંત્ર માટે નમ્ર.",
    "sizes.kicker": "બેગ સાઇઝ",
    "sizes.title": "તમારી યોગ્ય સાઇઝ શોધો",
    "sizes.sub": "બધી સાઇઝ 100% કમ્પોસ્ટેબલ અને ISO 17088:2021 પ્રમાણિત — કિરાણા દુકાનથી રિટેલ ચેન સુધી.",
    "sizes.chartTitle": "સાઇઝ ચાર્ટ",
    "sizes.chartSub": "કમ્પોસ્ટેબલ કેરી બેગ",
    "sizes.colSize": "સાઇઝ (ઇંચમાં)",
    "sizes.colMicron": "માઇક્રોન",
    "sizes.colPcs": "નંગ સંખ્યા (અંદાજે)",
    "sizes.colLoad": "લોડ ક્ષમતા",
    "sizes.custom": "કસ્ટમ સાઇઝ કે જથ્થાબંધ ભાવ જોઈએ છે?",
    "cta.enquiry": "પૂછપરછ મોકલો",
    "contact.kicker": "અમારા પાર્ટનર",
    "contact.title": "પાર્ટનર્સને મળો",
    "contact.sub": "અમારા પાર્ટનર્સનો સીધો સંપર્ક કરો — વિતરકો અને જાગૃત વ્યવસાયોને સાંભળવું અમને ગમે છે.",
    "vision.kicker": "અમારું વિઝન",
    "vision.title": "એક ટકાઉ ભવિષ્ય જે આપણે મળીને ઉભું કરી શકીએ",
    "vision.goalsTitle": "3-વર્ષીય અસર લક્ષ્યો",
    "vision.goal1.value": "100M",
    "vision.goal1.label": "દર વર્ષે બદલાતા પ્લાસ્ટિક બેગ",
    "vision.goal2.value": "5,000",
    "vision.goal2.label": "લેન્ડફિલમાં જતો કચરો ટળ્યો (ટન)",
    "vision.goal3.value": "500+",
    "vision.goal3.label": "સર્જાયેલી ગ્રીન નોકરીઓ",
    "vision.goal4.value": "1,000+",
    "vision.goal4.label": "સોર્સિંગ થકી સમર્થન મળતા ખેડૂતો",
    "vision.nationalTitle": "રાષ્ટ્રીય લક્ષ્યોમાં યોગદાન",
    "vision.national1.title": "2070 સુધી Net-Zero",
    "vision.national1.desc": "જૈવિક રીતે વિઘટિત વિકલ્પો થકી કાર્બન ફૂટપ્રિન્ટ ઘટાડવું.",
    "vision.national2.title": "સ્વચ્છ ભારત મિશન",
    "vision.national2.desc": "કચરો ઘટાડી સ્વચ્છ ભારત પહેલોને સમર્થન આપવું.",
    "vision.national3.title": "સર્ક્યુલર ઇકોનોમી",
    "vision.national3.desc": "ટકાઉ ઉત્પાદન અને ઉપભોગ ના પેટર્ન્સને પ્રોત્સાહન આપવું.",
    "vision.national4.title": "UN SDGs",
    "vision.national4.desc": "SDG 12 (જવાબદાર ઉપભોગ) અને SDG 13 (આબોહવા કાર્યવાહી) માં યોગદાન.",
    "vision.bannerTitle": "નવોપક્રમ અને પર્યાવરણીય જવાબદારી થકી ટકાઉ ભવિષ્ય બનાવવું",
    "vision.bannerCaption": "સ્કેલેબલ વિકલ્પો ત્યારે જ મહત્વપૂર્ણ બને છે જ્યારે તે ઉદ્યોગ, સમુદાય અને પૃથ્વી તમામને સાથ આપે છે.",
    "vision.whyTitle": "Bactofun Bags શા માટે મહત્વપૂર્ણ છે",
    "vision.why1.label": "પર્યાવરણીય સંકટ:",
    "vision.why1.desc": "ભારત દરરોજ 25,000 ટન પ્લાસ્ટિક કચરો ઉત્પન્ન કરે છે. અમે ઉપાયનો ભાગ છીએ.",
    "vision.why2.label": "નિયમનકીય દબાણ:",
    "vision.why2.desc": "2022 નો પ્લાસ્ટિક પ્રતિબંધ અનુરૂપ વિકલ્પો માટે તાત્કાલિક માંગ ઉભી કરે છે.",
    "vision.why3.label": "બજાર તક:",
    "vision.why3.desc": "$2.7B નું બજાર 12.08% CAGR સાથે વધી રહ્યું છે, જે વિશાળ પાયા પર વૃદ્ધિ ની સંભાવના દર્શાવે છે.",
    "vision.why4.label": "સામાજિક અસર:",
    "vision.why4.desc": "ગ્રીન રોજગાર બનાવવો અને ખેડૂતોની આજીવિકાને ટેકો આપવો.",
    "vision.why5.label": "ભવિષ્ય-તૈયાર:",
    "vision.why5.desc": "ભારતને ટકાઉ પેકેજિંગ નવોપક્રમમાં અગ્રણી તરીકે સ્થાપિત કરવું.",
    "vision.commitTitle": "અમારી પ્રતિબદ્ધતા",
    "vision.commit1": "ગુણવત્તામાં ઉત્કૃષ્ટતા",
    "vision.commit2": "પારદર્શક સોર્સિંગ",
    "vision.commit3": "પ્રમાણિત ઉત્પાદનો",
    "vision.commit4": "ગ્રાહક ભાગીદારી",
    "lang.label": "ભાષા",
  },
};

interface Ctx {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<Ctx | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    const saved = localStorage.getItem("ganesha-lang") as Lang | null;
    return saved && dictionaries[saved] ? saved : "en";
  });

  useEffect(() => {
    localStorage.setItem("ganesha-lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (nextLang: Lang) => setLangState(nextLang);
  const t = (key: string) => dictionaries[lang][key] ?? dictionaries.en[key] ?? key;

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
